### ISSUE TITLE
Composer installing old version

### ISSUE THREAD

**Issue by judodan** [crunzphp/crunz#11]
**Crunz version**: 2.3.1

**PHP version**: 7.4.29

**Operating system type and version**:

MacOS Monterey (also to be deployed on RH)

**Description**  
Composer installing older version of crunz. From CLI, I use `composer require crunzphp/crunz`  and it installs v 2.3.1, which is marked EOL on the repo.

**How to reproduce**  
from CLI, do `composer require crunzphp/crunz`

**Possible Solution**  
I could go into composer.json and change version by hand, but shouldn't that happen automatically?

**Additional context**  
I am using the latest version of composer. Not sure if the installed version might be dependent on what else I might have installed.

**Comment by PabloKowalczyk** [comment]
Hello, please paste your `composer.json` here.

**Comment by judodan** [comment]
This is what I have to after I require crunz

```
{
    ... 
    "autoload": {
        "psr-4": {
            "App\\": "app/src/"
        }
    },
    "require": {
        "monolog/monolog": ">=1.7.0",
        "phpmailer/phpmailer": "v6.0.7",
        "illuminate/database": ">=8.73.0",
        "crunzphp/crunz": "^2.3"
    }
}
```

**Comment by PabloKowalczyk** [comment]
In `composer.json` You require version `^2.3` which translates to `>=2.3.0 <3.0.0`, try to run `composer why-not crunzphp/crunz 3.2`, if there are no conflicts change version manually in `composer.json` and run `update`.

**Comment by judodan** [comment]
Turns out to be a case of PEBKAC.

Somehow I had my CLI PHP version pointing to a version of PHP 7.3. However, there's a little gain, I didn't know about the `why-not` for composer, that's a neat trick.  Thanks much!
