### ISSUE TITLE
Sub-minute scheduling

### ISSUE THREAD

**Issue by JonLaliberte** [crunzphp/crunz#12]
We can mimic this now, but it would be great if it were built in.

**Description**  
Technically jobs can only run every minute.

But it is possible to allow them to run, for example, every 30 seconds if you were to automatically schedule two jobs every minute, with one of them having a 30 second delay before executing.

So Job 1 runs immediately, Job 2 starts a 30 second timer, then runs. 
Bam, we're cooking at twice a speed 🔥

To do more frequent runs is similar, just needing to kick off as many jobs as needed with the requisite delays (or kick off one job that runs for the full minute and kicks off the jobs at the correct time - if doing this, technically any options are available for when to run).

**Example**  
```
$task = $schedule->run(PHP_BINARY . ' email.php');
$task->every[One|Two|Three|Four|Five|Six|Ten|Twelve|Fifteen|Twenty|Thirty]Seconds();
```

I think the best option is to allow any integer divisor of 60, so: 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30.

It could be that those shorter periods are too much - but a developer can decide that for themselves depending on what they're trying to accomplish.

Could also be something like:
```
$task = $schedule->run(PHP_BINARY . ' email.php');
$task       
    ->second([5, 10, 15, 20, 30])
    ->minute(['1-30', 45, 55])
    ->hour('1-5', 7, 8)
    ->dayOfMonth(12, 15)
    ->month(1);
```

This form may be confusing though if someone tries an invalid option for second.

**Comment by PabloKowalczyk** [comment]
Hot to implement it with Cron?

**Comment by JonLaliberte** [comment]
Mimic in cron would be something like this ([also here](https://stackoverflow.com/questions/9619362/running-a-cron-every-30-seconds)):

```
# Every 30 seconds
* * * * *             /usr/bin/php /path/to/email.php
* * * * * (sleep 30 ; /usr/bin/php /path/to/email.php )

# Every 15 seconds
* * * * *             /usr/bin/php /path/to/email.php
* * * * * (sleep 15 ; /usr/bin/php /path/to/email.php )
* * * * * (sleep 30 ; /usr/bin/php /path/to/email.php )
* * * * * (sleep 45 ; /usr/bin/php /path/to/email.php )
```

I think the best thing to do however would be for Cruz to stay running for 60 seconds and fire off those jobs at the correct sub-minute times. You could even keep Crunz running constantly to kick off any jobs (at which point you can support anything you want, including sub-minute scheduling), as long as there were a watchdog cron job to ensure Crunz is always running.

**Comment by PabloKowalczyk** [comment]
I see. What is your use case?

**Comment by JonLaliberte** [comment]
We have a queue that processes files. We want to check the queue more often than once per minute.

**Comment by judodan** [comment]
If you need to run that often, is cron based scheduling really the best tool? Sounds like it would be easier to have a program that constantly runs (and sleeps) in the background.

**Comment by JonLaliberte** [comment]
@judodan 🤔I was starting to think something similar, but the issue was created so I wanted to follow though on it. Realistically because of how simple of a job this is, we'll probably just go with the 30 second sleep kludge and call it a day.

**Comment by PabloKowalczyk** [comment]
As stated earlier it will be best to use software dedicated to queues (https://symfony.com/doc/current/messenger.html) or You can go fancy with daemon in ReactPHP/Swoole if you need (sub)second resolution.
