### ISSUE TITLE
Type error in str_replace call.

### ISSUE THREAD

**Issue by nhstephan** [crunzphp/crunz#14]
**Crunz version**: x.y.z
3.2.2

**PHP version**: x.y.z
8.1

**Operating system type and version**:
Ubuntu 22.04 LTS

**Description**
ProcessUtils::escapeArgument() is throwing a fatal error in PHP 8.1:

```
PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, bool given in vendor/crunzphp/crunz/src/ProcessUtils.php:84
```

**Comment by PabloKowalczyk** [comment]
Could you paste code to reproduce issue?

**Comment by nhstephan** [comment]
Apologies, the following should reproduce the issue. 

```php
$schedule = new Schedule();
$schedule->run(
    '/some/path/to/a/command',
    ['--someflag' => true]
)
...
```

The fatal error occurs when a boolean is passed instead of an expected string value. A solution would be to pass the boolean as a string (e.g. `'true'`) for the parameter, however this doesn't solve the problem of ambiguous typecasting in ProcessUtils if a non-string value is passed ... which now throws a fatal error in PHP 8.x. In ProcessUtils you may wish to add more type checking before passing parameters to native functions like str_replace.

**Comment by PabloKowalczyk** [comment]
Looks like Crunz tried to support `['--option' => 'value']`, but it doesn't work like that in Process (https://symfony.com/doc/current/components/process.html) and this behavior (non-list array) should be deprecated, also `\Crunz\Schedule::run` method has docblock with `@param string[] $parameters` which clearly expects list of string values.

If you really want (do you?) I can convert boolean values to string `1` and `0` for now, but `v3.3` will deprecate passing non-list arrays.

**Comment by nhstephan** [comment]
OK, thanks for the information. I will close the issue since the behavior is being deprecated.
