### ISSUE TITLE
Closures don't run in parallel

### ISSUE THREAD

**Issue by kpconnell** [crunzphp/crunz#26]
Might want to notate that closures don't run in parallel (at least on windows).  php binaries/other commands do.

**Comment by PabloKowalczyk** [comment]
Hello, could you paste some code to reproduce issue?

**Comment by kpconnell** [comment]
These will run one at at a time and the total time of the scheduled run will be 10*len($arr) seconds.

```
foreach($arr as $item)
{

    $task = $schedule->run(function() use ($item) { 

      sleep(10);

    
    });
  $task
    
       ->everyMinute()
        ->description($item["name"])
        ->appendOutputTo("/tmp/". $item["name"] . ".txt");
        




}
return $schedule

**Comment by PabloKowalczyk** [comment]
Tested on v3.3 and works as expected on WIndows. What version are you using (Crunz and PHP)?
You can run Crunz with `schedule:run -vvv` to get some debug info, also there is `task:debug` command to get more info about specific task, maybe `preventOverlapping` is enabled?
Currently doesn't look like issue in Crunz.

Here is my reproducing code:
```php
<?php

use Crunz\Schedule;

$scheduler = new Schedule();

$closure = function (): void {
    \sleep(3);

    echo 'Done', PHP_EOL;
};

for ($i = 1; $i <= 2; $i++) {
    $event = $scheduler->run($closure);
    $event
        ->everyMinute()
        ->description("Closure {$i}")
        ->appendOutputTo("/tmp/closure-{$i}.txt")
    ;
}

return $scheduler;

```
