### ISSUE TITLE
Dont fail if one Task file throws an exception

### ISSUE THREAD

**Issue by turtle0x1** [crunzphp/crunz#29]
If you have a `...Task.php` file that throws an exception, none of the jobs run.

Ive been stung by this in past and without being able to call the task pragmatically (or atleast I cant work out how) you have to-do extra work to make sure this isn't preventing your jobs from being run.

Could try to submit a PR but would need some pointers :smile:

**Comment by PabloKowalczyk** [comment]
Crunz could do some `try/catch` magic, but it's tricky, it will be better to handle this situation in script.
