### ISSUE TITLE
Running task in sequence 

### ISSUE THREAD

**Issue by gabbykweka** [crunzphp/crunz#30]
I been trying to run task in serialize manner. Meaning after the first task is done should run another schedule task. Is this possible? Using the after function seems to fail with error  _Call to a member function isRunning() on null_  

The second command depends on the result processed from the first command.

**Comment by PabloKowalczyk** [comment]
Hello, Crunz is designed to run all tasks in parallel (same as Cron), so there is no way to "run task after other taks", but you can use Unix's `&&`, for example `mkdir test && cd test`, or you can write PHP script that will run two commands.

> The second command depends on the result processed from the first command.

In this case Unix's pipe `|` looks like ideal candidate.

**Comment by gabbykweka** [comment]
Thank you for the feedback! Will test the && and see the output of it!
