### ISSUE TITLE
Documentation: RetryTillSaveStore has been removed from Symfony/lock

### ISSUE THREAD

**Issue by dbaggott** [crunzphp/crunz#34]
**Description**  

The documentation indicates that `RetryTillSaveStore` from Symfony should be used to prevent overlapping executions.  However, that class was deprecated in 5.2 and, [as of 6.0](https://github.com/symfony/lock/blob/6.1/CHANGELOG.md#60), it no longer exists.

The functionality has been moved into `Lock`.

Update documentation accordingly.

**Comment by PabloKowalczyk** [comment]
Turns out there is no need to force using "blocking" store, this is why I removed section.
