### ISSUE TITLE
how to set errors_log_file and output_log_file to save relative to the project.

### ISSUE THREAD

**Issue by klytron** [crunzphp/crunz#74]
I want to set the log files in the config relative to the project in the logs folder.

crunz.yml

log_errors: true
errors_log_file:logs/error.log
log_output: true
output_log_file: logs/output.log

Project Folder Structure
- vendor
- logs
- tasks
- crunz.yml
-

**Comment by PabloKowalczyk** [comment]
Hello, paths in `errors_log_file` and `output_log_file` are relative to project (to `crunz.yml` actually).

**Comment by klytron** [comment]
yes thank you i tested it, works fine as configured.
